set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g mouse on
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g renumber-windows on
set -g set-clipboard on
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'


#swap-windows
bind -r "1" swap-window -d -t :1
bind -r "2" swap-window -d -t :2
bind -r "3" swap-window -d -t :3
bind -r "4" swap-window -d -t :4
bind -r "5" swap-window -d -t :5
bind -r "6" swap-window -d -t :6
bind -r "7" swap-window -d -t :7
bind -r "8" swap-window -d -t :8
bind -r "9" swap-window -d -t :9


#select-windows
bind -r "&" select-window -t 1
bind -r "é" select-window -t 2
bind -r '"' select-window -t 3
bind -r "'" select-window -t 4
bind -r "(" select-window -t 5
bind -r "-" select-window -t 6
bind -r "è" select-window -t 7
bind -r "_" select-window -t 8
bind -r "ç" select-window -t 9
